// vue3&react18/source_code/13 - Vue3+TS4项目 - 添加审批页与我的审批页实现/vue-ts-app-version4/src/views/Home/components/HomeAside.vue
<template>
  <el-menu :default-active="route.path" router>
    <el-sub-menu v-for="item in menus" :key="item.path" :index="item.path">
      <template #title>
        <el-icon><component :is="item.meta?.icon"></component></el-icon>
        <span>{{ item.meta?.title }}</span>
      </template>
      <el-menu-item v-for="itemChild in item.children" :key="item.path + itemChild.path" :index="item.path + itemChild.path">
        <el-icon><component :is="itemChild.meta?.icon"></component></el-icon>
        <span>{{ itemChild.meta?.title }}</span> 
      </el-menu-item>
    </el-sub-menu>
  </el-menu>
</template>

<script setup lang="ts">
import _ from 'lodash'
import { useRouter, useRoute } from 'vue-router';
import type { RouteRecordName } from 'vue-router';
import { useStore } from '@/store';

const router = useRouter();
const route = useRoute();
const store = useStore();
const permission = store.state.users.infos.permission;

const menus = _.cloneDeep(router.options.routes).filter((v)=> {

  v.children = v.children?.filter((v)=> v.meta?.menu && (permission as (RouteRecordName|undefined)[]).includes(v.name));

  return v.meta?.menu && (permission as (RouteRecordName|undefined)[]).includes(v.name);
})


</script>

<style scoped lang="scss">

.el-menu{
  height: calc(100vh - 60px);
  border: none;
  padding-top: 30px;
}
.el-menu-item.is-active{
  background: #e6f7ff;
  border-right: 3px solid #1890ff;
}
</style>

// vue3&react18/source_code/20 - React18+TS4项目 - 登录页与首页实现/react-ts-app-version2/src/views/Home/components/HomeAside.tsx
import React from 'react'
import { Menu } from 'antd'
import type { MenuProps } from 'antd';
import styles from '../Home.module.scss'
import { routes } from '../../../router';
import { useSelector } from 'react-redux';
import type { RootState } from '../../../store';
import _ from 'lodash'
import { useLocation, matchRoutes, Link } from 'react-router-dom'

export default function HomeAside() {
  const permission = useSelector((state: RootState)=> state.users.infos.permission) as unknown[]
  const location = useLocation()
  const matchs = matchRoutes(routes, location)
  const subPath = matchs![0].pathnameBase || '';
  const path = matchs![1].pathnameBase || '';
  const menus = _.cloneDeep(routes).filter((v)=> {
    v.children = v.children?.filter((v)=> v.meta?.menu && permission.includes(v.name))
    return v.meta?.menu && permission.includes(v.name)
  })

  const items: MenuProps['items'] = menus.map((v1)=>{
    const children = v1.children?.map((v2)=>{
      return {
        key: v1.path! + v2.path!,
        label: <Link to={v1.path! + v2.path!}>{v2.meta?.title}</Link>,
        icon: v2.meta?.icon
      }
    })
    return {
      key: v1.path!,
      label: v1.meta?.title,
      icon: v1.meta?.icon,
      children
    }
  })

  return (
    <Menu
      defaultSelectedKeys={[path]}
      defaultOpenKeys={[subPath]}
      mode="inline"
      items={items}
      className={styles['home-aside']}
    />
  )
}
