// vue3&react18/source_code/13 - Vue3+TS4项目 - 添加审批页与我的审批页实现/vue-ts-app-项目优化一/src/views/Home/components/HomeHeader.vue
<template>
  <div class="home-header">
    <span class="home-header-logo">
      <i class="iconfont icon-vue"></i>
      <i class="iconfont icon-icon-test"></i>
      <i class="iconfont icon-typescript"></i>
    </span>
    <span class="home-header-title">在线考勤系统</span>
    <el-dropdown>
      <el-badge :is-dot="isDot">
        <el-icon :size="20"><Bell /></el-icon>
      </el-badge>
      <template #dropdown>
        <el-dropdown-menu>
          <el-dropdown-item @click="handleNavigate('/apply')" v-if="newsInfo.applicant">有审批结果消息</el-dropdown-item>
          <el-dropdown-item @click="handleNavigate('/check')" v-if="newsInfo.approver">有审批请求消息</el-dropdown-item>
          <el-dropdown-item v-if="!newsInfo.applicant && !newsInfo.approver">暂无消息</el-dropdown-item>
        </el-dropdown-menu>
      </template>
    </el-dropdown>
    <el-dropdown>
      <el-space class="home-header-space">
        <el-avatar :src="(head as string)" /> {{ name }}
      </el-space>
      <template #dropdown>
        <el-dropdown-menu>
          <el-dropdown-item>个人中心</el-dropdown-item>
          <el-dropdown-item @click="handleLogout">退出</el-dropdown-item>
        </el-dropdown-menu>
      </template>
    </el-dropdown>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useStore } from '@/store';
import { useRouter } from 'vue-router';
const store = useStore();
const router = useRouter();
const head = computed(()=> store.state.users.infos.head)
const name = computed(()=> store.state.users.infos.name)

const newsInfo = computed(()=> store.state.news.info)
const isDot = computed(()=> (newsInfo.value.applicant || newsInfo.value.approver) as boolean)

const handleLogout = () => {
  store.commit('users/clearToken')
  setTimeout(()=>{
    window.location.replace('/login')
  }, 500)
}
const handleNavigate = (path: string) => {
  router.push(path);
}
</script>

<style scoped lang="scss">
.home-header{
  font-size: 34px;
  display: flex;
  align-items: center;
  height: 100%;
  .home-header-logo {
      .icon-vue,
      .icon-icon-test,
      .icon-typescript {
        margin-right: 5px;
        font-size: inherit;
      }
      .icon-vue {
        color: green;
      }
      .icon-icon-test {
        color: #deb887;
      }
      .icon-typescript {
        color: blue;
      }
    }
    .home-header-title {
      margin-left: 30px;
      font-weight: 700;
      font-size: 18px;
      margin-right: auto;
    }
    .home-header-space{
      margin-left: 20px;
    }
}
</style>

// vue3&react18/source_code/22 - React18+TS4项目 - 添加审批页与我的审批页实现/react-ts-app-version4/src/views/Home/components/HomeHeader.tsx
import React, { useEffect } from 'react'
import styles from '../Home.module.scss'
import classNames from 'classnames'
import { Dropdown, Badge, Space, Avatar } from 'antd'
import type { MenuProps } from 'antd';
import { BellOutlined } from '@ant-design/icons'
import { useSelector } from 'react-redux';
import { useAppDispatch } from '../../../store';
import type { RootState } from '../../../store';
import { clearToken } from '../../../store/modules/users';
import { getRemindAction, updateInfo } from '../../../store/modules/news';
import type { Info } from '../../../store/modules/news';
import { Link } from 'react-router-dom';

export default function HomeHeader() {
  const name = useSelector((state: RootState)=> state.users.infos.name) as string 
  const head = useSelector((state: RootState)=> state.users.infos.head) as string
  const _id = useSelector((state: RootState)=> state.users.infos._id) as string
  const newsInfo = useSelector((state: RootState)=> state.news.info)
  const dispatch = useAppDispatch()

  const isDot = (newsInfo.applicant || newsInfo.approver) as boolean | undefined;

  useEffect(()=>{
    dispatch(getRemindAction({userid: _id})).then((action)=>{
      const { errcode, info } = (
        action.payload as { [index: string]: unknown }
      ).data as { [index: string]: unknown }
      if (errcode === 0) {
        dispatch(updateInfo(info as Info))
      }
    })
  }, [dispatch, _id])

  const handleLogut = () => {
    dispatch(clearToken())
    setTimeout(()=>{
      window.location.replace('/login')
    })
  }

  const items1: MenuProps['items'] = []

  if( newsInfo.applicant ){
    items1.push({
      key: '1',
      label: <Link to="/apply">有审批结果消息</Link>
    })
  }
  if( newsInfo.approver ){
    items1.push({
      key: '2',
      label: <Link to="/check">有审批请求消息</Link>
    })
  }
  if(!newsInfo.applicant && !newsInfo.approver){
    items1.push({
      key: '3',
      label: <div>暂无消息</div>
    })
  }

  const items2: MenuProps['items'] = [
    {
      key: '1',
      label: (
        <div>个人中心</div>
      ),
    },
    {
      key: '2',
      label: (
        <div onClick={handleLogut}>退出</div>
      ),
    }
  ]

  return (
    <div className={styles['home-header']}>
      <span className={styles['home-header-logo']}>
        <i className={classNames('iconfont icon-react', styles['icon-react'])}></i>
        <i className={classNames('iconfont icon-icon-test', styles['icon-icon-test'])}></i>
        <i className={classNames('iconfont icon-typescript', styles['icon-typescript'])}></i>
      </span>
      <span className={styles['home-header-title']}>在线考勤系统</span>
      <Dropdown menu={{ items: items1 }} arrow placement="bottom">
        <Badge dot={isDot}>
          <BellOutlined style={{ fontSize: 20 }} />
        </Badge>
      </Dropdown>
      <Dropdown menu={{ items: items2 }} arrow placement="bottom">
        <Space className={styles['home-header-space']}>
          <Avatar src={head} size="large" /> {name}
        </Space>
      </Dropdown>
    </div>
  )
}
