// vue3&react18/source_code/21 - React18+TS4项目 - 打卡签到页与异常考勤页实现/react-ts-app-version3/src/views/Exception/Exception.tsx
import React, { useState, useEffect } from 'react'
import styles from './Exception.module.scss'
import { Row, Col, Button, Select, Space, Empty, Timeline, Card } from 'antd'
import { Link, useSearchParams } from 'react-router-dom'
import { useSelector } from 'react-redux'
import { useAppDispatch } from '../../store'
import type { RootState } from '../../store'
import _ from 'lodash'
import {
  getTimeAction,
  updateInfos,
} from '../../store/modules/signs'
import type { Infos } from '../../store/modules/signs'
import { toZero } from '../../utils/common'

let date = new Date()
let year = date.getFullYear()

export default function Exception() {
  const [searchParams, setSearchParams] = useSearchParams()
  const [month, setMonth] = useState( searchParams.get('month') ? Number(searchParams.get('month')) - 1 : date.getMonth())
  const signsInfos = useSelector((state: RootState)=> state.signs.infos)
  const usersInfos = useSelector((state: RootState)=> state.users.infos)
  const dispatch = useAppDispatch()
  useEffect(() => {
    if (_.isEmpty(signsInfos)) {
      dispatch(getTimeAction({ userid: usersInfos._id as string })).then(
        (action) => {
          const { errcode, infos } = (
            action.payload as { [index: string]: unknown }
          ).data as { [index: string]: unknown }
          if (errcode === 0) {
            dispatch(updateInfos(infos as Infos))
          }
        }
      )
    }
  }, [signsInfos, usersInfos, dispatch])

  let details;
  if(signsInfos.detail){
    const detailMonth = (signsInfos.detail as { [index: string]: unknown })[
      toZero(month + 1)
    ] as { [index: string]: string }
    details = Object.entries(detailMonth).filter((v)=> v[1]!=='正常出勤').sort()
  }

  const handleChange = (value: number) => {
    setMonth(value)
    setSearchParams({month: String(value+1)})
  }
  const renderTime = (date: string) => {
    const ret = ((signsInfos.time as {[index: string]: unknown})[toZero(month+1)] as {[index: string]: unknown})[date];
    if( Array.isArray(ret) ){
      return ret.join('-');
    }
    else{
      return '暂无打卡记录';
    }
  }
  const monthOptions = [];
  for(let i=0;i<12;i++){
    monthOptions.push(<Select.Option key={i} value={i}>{i+1}月</Select.Option>)
  }
  return (
    <div className={styles.exception}>
      <Row justify="space-between" align="middle">
        <Link to="/apply">
          <Button type="primary">异常处理</Button>
        </Link>
        <Space>
          <Button>{year}年</Button>
          <Select value={month} onChange={handleChange}>
            {monthOptions}
          </Select>
        </Space>
      </Row>
      <Row className={styles['exception-line']} gutter={20}>
        <Col span={12}>
          {
            details
            ?
            <Timeline>
              {
                details.map((item)=> {
                  return (
                    <Timeline.Item key={item[0]}>
                      <h3>{year}/{month+1}/{item[0]}</h3>
                      <Card className={styles['exception-card']}>
                        <Space>
                          <h4>{item[1]}</h4>
                          <p>考勤详情：{renderTime(item[0])}</p>
                        </Space>
                      </Card>
                    </Timeline.Item>
                  )
                })
              }
            </Timeline>
            :
            <Empty description="暂无异常考勤" imageStyle={{height: 200}} />
          }
        </Col>
        <Col span={12}>
          {/* <Empty description="暂无申请审批" imageStyle={{height: 200}} /> */}
          <Timeline>
            <Timeline.Item>
              <h3>事假</h3>
              <Card className={styles['exception-card']}>
                <h4>待审批</h4>
                <p className={styles['exception-content']}>申请日期 2022-12-08 09:08:09 - 2022-12-09 09:08:12</p>
                <p className={styles['exception-content']}>申请详情 aaa</p>
              </Card>
            </Timeline.Item>
            <Timeline.Item>
              <h3>事假</h3>
              <Card className={styles['exception-card']}>
                <h4>待审批</h4>
                <p className={styles['exception-content']}>申请日期 2022-12-08 09:08:09 - 2022-12-09 09:08:12</p>
                <p className={styles['exception-content']}>申请详情 aaa</p>
              </Card>
            </Timeline.Item>
          </Timeline>
        </Col>
      </Row>
    </div>
  )
}

// vue3&react18/source_code/13 - Vue3+TS4项目 - 添加审批页与我的审批页实现/vue-ts-app-项目优化一/src/views/Exception/Exception.vue
<template>
  <div class="exception-title">
    <el-button type="primary" @click="handleToApply">异常处理</el-button>
    <el-space>
      <el-button plain>{{ year }}年</el-button>
      <el-select v-model="month">
        <el-option v-for="item in 12" :key="item" :value="item" :label="item + '月'" />
      </el-select>
    </el-space>
  </div>
  <el-row :gutter="20">
    <el-col :span="12">
      <el-empty v-if="detailMonth.length === 0" description="暂无异常考勤" />
      <el-timeline v-else>
        <el-timeline-item v-for="item in detailMonth" :key="item[0]" :timestamp="year + '/' + month + '/' + item[0]" placement="top">
          <el-card>
            <el-space>
              <h4>{{ item[1] }}</h4>
              <p>考勤详情：{{ renderTime(item[0]) }}</p>
            </el-space>
          </el-card>
        </el-timeline-item>
      </el-timeline>
    </el-col>
    <el-col :span="12">
      <el-empty v-if="applyListMonth.length === 0" description="暂无申请审批" />
      <el-timeline v-else>
        <el-timeline-item v-for="item in applyListMonth" :key="(item._id as string)" :timestamp="(item.reason as string)" placement="top">
          <el-card>
            <h4>{{ item.state }}</h4>
            <p class="apply-info">申请日期 {{ (item.time as string[])[0] }} - {{ (item.time as string[])[1] }}</p>
            <p class="apply-info">申请详情 {{ item.note }}</p>
          </el-card>
        </el-timeline-item>
        <el-timeline-item timestamp="事假" placement="top">
          <el-card>
            <h4>已通过</h4>
            <p class="apply-info">申请日期 2022-10-01 12:00:00 - 2022-11-08 12:00:00</p>
            <p class="apply-info">申请详情 123</p>
          </el-card>
        </el-timeline-item>
      </el-timeline>
    </el-col>
  </el-row>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useStore } from '@/store'
import { toZero } from '@/utils/common'

const route = useRoute()
const router = useRouter()
const store = useStore()

const signsInfos = computed(() => store.state.signs.infos)

const date = new Date();
const year = date.getFullYear();
const month = ref( Number(route.query.month) || date.getMonth() + 1 )

const applyListMonth = computed(() => store.state.checks.applyList.filter((v) => {
  const startTime = (v.time as string[])[0].split(' ')[0].split('-');
  const endTime = (v.time as string[])[1].split(' ')[0].split('-');
  return startTime[1] <= toZero(month.value) && endTime[1] >= toZero(month.value)
}))

const ret = ((signsInfos.value.detail as {[index: string]: unknown})[toZero(month.value)] as {[index: string]: unknown})
const detailMonth = computed(() => Object.entries(ret).filter((v)=> v[1] !== '正常出勤').sort())

watch(month, ()=>{
  router.push({
    query: { month: month.value }
  });
})

const handleToApply = () => {
  router.push('/apply');
}

const renderTime = (date: string) => {
  const ret = ((signsInfos.value.time as {[index: string]: unknown})[toZero(month.value)] as {[index: string]: unknown})[date];
  if( Array.isArray(ret) ){
    return ret.join('-');
  }
  else{
    return '暂无打卡记录';
  }
}

</script>

<style scoped lang="scss">
.exception-title{
  margin: 20px;
  display: flex;
  justify-content: space-between;
}
.el-select{
  width: 80px;
}
.el-timeline{
  margin: 10px;
}
.apply-info{
  margin: 10px;
}
</style>
